/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "phenix.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
test_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		Partenaire inscription_1_arg;
		Connexion_param connexion_1_arg;
		Search_Param cln_recherche_partenaire_1_arg;
		int cln_recherche_pannier_1_arg;
		int cln_commande_pannier_1_arg;
		Change_profil_param modifier_profil_1_arg;
		Pannier part_ajouter_pannier_1_arg;
		Pannier part_modifier_pannier_1_arg;
		int part_supprimer_pannier_1_arg;
		Coordonnee cln_reecherche_pannier_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case init:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) init_1_svc;
		break;

	case inscription:
		_xdr_argument = (xdrproc_t) xdr_Partenaire;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) inscription_1_svc;
		break;

	case connexion:
		_xdr_argument = (xdrproc_t) xdr_Connexion_param;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) connexion_1_svc;
		break;

	case cln_recherche_partenaire:
		_xdr_argument = (xdrproc_t) xdr_Search_Param;
		_xdr_result = (xdrproc_t) xdr_Tab_int;
		local = (char *(*)(char *, struct svc_req *)) cln_recherche_partenaire_1_svc;
		break;

	case cln_recherche_pannier:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Tab_int;
		local = (char *(*)(char *, struct svc_req *)) cln_recherche_pannier_1_svc;
		break;

	case cln_commande_pannier:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) cln_commande_pannier_1_svc;
		break;

	case cln_historique_commande:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_Tab_int;
		local = (char *(*)(char *, struct svc_req *)) cln_historique_commande_1_svc;
		break;

	case modifier_profil:
		_xdr_argument = (xdrproc_t) xdr_Change_profil_param;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) modifier_profil_1_svc;
		break;

	case part_ajouter_pannier:
		_xdr_argument = (xdrproc_t) xdr_Pannier;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) part_ajouter_pannier_1_svc;
		break;

	case part_modifier_pannier:
		_xdr_argument = (xdrproc_t) xdr_Pannier;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) part_modifier_pannier_1_svc;
		break;

	case part_supprimer_pannier:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) part_supprimer_pannier_1_svc;
		break;

	case part_liste_pannier:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_Tab_int;
		local = (char *(*)(char *, struct svc_req *)) part_liste_pannier_1_svc;
		break;

	case cln_reecherche_pannier:
		_xdr_argument = (xdrproc_t) xdr_Coordonnee;
		_xdr_result = (xdrproc_t) xdr_Tab_int;
		local = (char *(*)(char *, struct svc_req *)) cln_reecherche_pannier_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (TEST, phenix);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TEST, phenix, test_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TEST, phenix, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TEST, phenix, test_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TEST, phenix, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
